### PR TITLE
adding logformat and fixing the install of libssl

### PR DESCRIPTION
**Pull request by prometheanfire**

### CODE REVIEW

**Comment by prometheanfire** [comment]
needs https://github.com/rackspace-cookbooks/percona-multi/pull/4 to be published

**Comment by RichieSM** [comment]
Hi @prometheanfire 

We need this merged in as soon as possible.
To fix your build (unit test) error, add this at line 30 of test/unit/spec/default_spec.rb:

    stub_command("ls /recovery.conf").and_return(0)

**Comment by prometheanfire** [comment]
it is more then just that, 14.04 is failing with an a2enmod error

**Comment by jujugrrr** [comment]
@prometheanfire , @cybermerc : https://github.com/rackspace-cookbooks/phpstack/commit/9ba32319f5a15f02ff5338cd751bff1b439bf320 is not a backward compatible change. I'm commenting why on the commit.

We need to address : 

* why did we only pin for a patch version
* why did we have that many breaking changes in 4.0.1 (https://github.com/rackspace-cookbooks/phpstack/commit/5be27e8687fb6585ff5b1813399aaae875c3cc94 is a pretty big one as well, it's fixing a bug but at the same time it stopped to use platformstack::iptables and platformstack::monitor) 
* why didn't we catch this specific PR will be a breaking change (tests)
* why didn't we catch it was an important change during peer review

**Comment by martinb3** [comment]
:+1: to the problem of a breaking change without a major version bump -- we get a lot of complaints about phpstack, and I think the constant, regular stream of breaking changes the majority of the reason.

Also, the CHANGELOG.md entries for 4.0.0 and 4.0.1 are also badly formatted markdown (missing newlines).

**Comment by prometheanfire** [comment]
* The change is backwards compatible in the default use case.
* setting the version bump as a patch bump was likely wrong, setting it as major would also likely be wrong.  I think if the default behaviour stays the same it should be at most a minor bump, which I feel this should have been.
* we had so many 'breaking' changes in 4.0.1 because no one else did a release before my pull request.
* I was not responsible for code review
* ^

This change was meant to be a drop in replacement for the older way of doing things.  I suppose I could make this a major version bump instead, but this feels much more like a minor version bump maybe.  If we are adding / splitting an attribute like we are doing now, does that ALWAYS require a major version bump?  If so, we will be doing that every couple of pull requests.

Changelog formatting was kept the same.

**Comment by martinb3** [comment]
> The change is backwards compatible in the default use case.

I'm not sure what that means. Are you saying if they didn't change the default value, it was backwards compatible?

**Comment by prometheanfire** [comment]
The default use case is the stack choosing the location of were the site goes and the code goes.  Before it was  /var/www/sitename/portnumber for the code (/current being for the current checkout) and /current being where the web server looked as well.  Those locations did not change.

**Comment by martinb3** [comment]
I think I still disagree; the fact that the document root location changed on disk feels like a backwards-incompatible change, as that's critical information for most customers:
```
- DocumentRoot <%= @params[:docroot] %>/current
+ DocumentRoot <%= @params[:docroot] %>
```

**Comment by prometheanfire** [comment]
the docroot was previously default to ' /var/www/sitename/portnumber/current' (the /current part being static).

the docroot is now defaulting to ' /var/www/sitename/portnumber/current'.

**Pull request merged**
