### PR TITLE
Revert "Revert "remove static assignment to (dir)/current in templates""

### PR DESCRIPTION
**Pull request by prometheanfire**
This reverts commit 412f3acbd3b0977ac0d5d88510ea64e7ec90f353.

This should be a major version bump

* Allows the setting of user/group to be separate from the web server user/group
* Separates the location for the deployed code and the http server's docroot

Signed-off-by: Matthew Thode <mthode@mthode.org>

### CODE REVIEW

**Comment by prometheanfire** [comment]
well, uk, how do you feel about this.

@jujugrrr @niven01

**Comment by martinb3** [comment]
https://github.com/rackspace-cookbooks/phpstack#useful-datastructures section of the README probably needs to be updated to show that an attribute has a new default value & to document the two new attributes.

**Comment by prometheanfire** [comment]
ok

**Comment by jujugrrr** [comment]
Hi
Please see my comment on #291.

I'd like to close this PR (not merge it)

**Comment by prometheanfire** [comment]
should I close all feature request issues then?

**Comment by martinb3** [comment]
I would keep feature requests until we can figure out how to apply them to each library implementation.

**Pull request closed without merging**
